language: objective-c
before_install:
  - env
  - sw_vers -productVersion | grep -E '^10\.[89]' > /dev/null && bash -c "[ -d /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain ] && sudo -u $(ls -ld /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain | awk '{print $3}') bash -c 'ln -vs XcodeDefault.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -c-4).xctoolchain' || sudo bash -c 'mkdir -vp /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -c-4).xctoolchain/usr && ln -s /usr/bin /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -c-4).xctoolchain/usr/bin'"
  - brew update
  - brew tap homebrew/homebrew-dupes
install:
  - mkdir -pv $(brew --repo)/Library/Taps/travis
  - ln -sv $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
env:
  - PACKAGE="ab"
  - PACKAGE="apr"
  - PACKAGE="apr-util"
  - PACKAGE="httpd22"
  - PACKAGE="httpd22 --with-brewed-openssl"
  - PACKAGE="httpd22 --with-pcre"
  - PACKAGE="httpd22 --with-brewed-openssl --with-pcre"
  - PACKAGE="httpd24"
  - PACKAGE="httpd24 --with-brewed-openssl"
  - PACKAGE="mod_bonjour"
  - PACKAGE="mod_bonjour --with-brewed-httpd22"
  - PACKAGE="mod_bonjour --with-brewed-httpd24"
  - PACKAGE="mod_fastcgi"
  - PACKAGE="mod_fastcgi --with-brewed-httpd22"
  - PACKAGE="mod_fastcgi --with-brewed-httpd24"
  - PACKAGE="mod_fcgid"
  - PACKAGE="mod_fcgid --with-brewed-httpd22"
  - PACKAGE="mod_fcgid --with-brewed-httpd24"
  - PACKAGE="mod_python"
  - PACKAGE="mod_python --with-brewed-httpd22"
  - PACKAGE="mod_python --with-brewed-httpd24"
  - PACKAGE="mod_python --with-brewed-httpd22 --with-brewed-python"
  - PACKAGE="mod_python --with-brewed-httpd24 --with-brewed-python"
  - PACKAGE="mod_security"
  - PACKAGE="mod_security --with-brewed-apr"
  - PACKAGE="mod_security --with-brewed-httpd22"
  - PACKAGE="mod_security --with-brewed-httpd24"
  - PACKAGE="mod_wsgi"
  - PACKAGE="mod_wsgi --with-brewed-httpd22"
  - PACKAGE="mod_wsgi --with-brewed-httpd24"
  - PACKAGE="mod_wsgi --with-brewed-httpd22 --with-brewed-python"
  - PACKAGE="mod_wsgi --with-brewed-httpd24 --with-brewed-python"
script:
  - brew install -v $PACKAGE
